dist: xenial
language: python
python:
    - "3.7"
    - "3.8"
    - "3.9"
    - "3.10"
install:
    - pip install --upgrade pip setuptools
    - pip install -r dev-requirements.txt
    - pip install -e .
    - pip list
env:
  global:
    - CIVIS_API_KEY=FOOBAR
before_script: flake8 civis
script:
    - py.test -rxs --cov civis
    - if [[ $TRAVIS_PYTHON_VERSION == 3.8* ]] ; then sphinx-build -b html -n docs/source/ docs/build/ ; fi
