language: python
python:
    - "2.7"
    - "3.4"
install:
    - pip install --upgrade pip setuptools
    - pip install -r requirements.txt
    - pip install -r dev-requirements.txt
    - pip install -e .[pubnub]
env:
  global:
    - CIVIS_API_KEY=FOOBAR
before_script: flake8 civis
script:
    - py.test --cov civis
    - sphinx-build -b html -n docs/source/ docs/build/
