build: false  # Not a .NET project


environment:
  # For python environments: https://www.appveyor.com/docs/build-environment/#python
  matrix:
    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.15"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.4"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.3"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.5"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.2"
      PYTHON_ARCH: "64"

  # Environmental variables
  CIVIS_API_KEY: "FOOBAR"


init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"


install:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip setuptools"
  - "%PYTHON%\\python.exe -m pip install -r dev-requirements.txt"
  - "%PYTHON%\\python.exe -m pip install -e ."


test_script:
  - "%PYTHON%\\Scripts\\flake8.exe civis"
  - "%PYTHON%\\Scripts\\pytest.exe -rxXs --cov civis"
