name: wbcd_demo
channels: !!python/tuple
- conda-forge
- defaults
dependencies:
- appnope=0.1.0=py36_0
- blas=1.1=openblas
- bleach=1.5.0=py36_0
- ca-certificates=2017.1.23=1
- certifi=2017.4.17=py36_0
- cycler=0.10.0=py36_0
- dbus=1.10.10=3
- decorator=4.0.11=py36_0
- entrypoints=0.2.2=py36_1
- expat=2.1.0=2
- freetype=2.7=1
- html5lib=0.999=py36_0
- icu=58.1=1
- ipykernel=4.6.1=py36_0
- ipython=6.0.0=py36_0
- ipython_genutils=0.2.0=py36_0
- ipywidgets=6.0.0=py36_0
- jedi=0.10.0=py36_0
- jinja2=2.9.5=py36_0
- joblib=0.11=py36_0
- jpeg=9b=0
- jsonschema=2.5.1=py36_0
- jupyter=1.0.0=py36_0
- jupyter_client=5.0.1=py36_0
- jupyter_console=5.1.0=py36_0
- jupyter_core=4.3.0=py36_0
- libgfortran=3.0.0=0
- libpng=1.6.28=0
- libsodium=1.0.10=0
- markupsafe=0.23=py36_1
- matplotlib=2.0.1=np112py36_0
- mistune=0.7.4=py36_0
- nbconvert=5.1.1=py36_1
- nbformat=4.3.0=py36_0
- nbstripout=0.3.0=py36_0
- ncurses=5.9=10
- notebook=5.0.0=py36_0
- numpy=1.12.1=py36_blas_openblas_200
- openblas=0.2.19=2
- openssl=1.0.2k=0
- pandas=0.19.2=np112py36_1
- pandoc=1.19.2=0
- pandocfilters=1.4.1=py36_0
- pexpect=4.2.1=py36_0
- pickleshare=0.7.3=py36_0
- pip=9.0.1=py36_0
- prompt_toolkit=1.0.14=py36_0
- ptyprocess=0.5.1=py36_0
- pygments=2.2.0=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_2
- python=3.6.1=0
- python-dateutil=2.6.0=py36_0
- pytz=2017.2=py36_0
- pyzmq=16.0.2=py36_1
- qt=5.6.2=1
- qtconsole=4.3.0=py36_0
- readline=6.2=0
- requests=2.13.0=py36_0
- scikit-learn=0.18.1=np112py36_blas_openblas_200
- scipy=0.19.0=np112py36_blas_openblas_200
- setuptools=33.1.1=py36_0
- simplegeneric=0.8.1=py36_0
- sip=4.18=py36_1
- six=1.10.0=py36_1
- sqlite=3.13.0=1
- terminado=0.6=py36_0
- testpath=0.3=py36_0
- tk=8.5.19=1
- tornado=4.5.1=py36_0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- webencodings=0.5=py36_0
- wheel=0.29.0=py36_0
- widgetsnbextension=2.0.0=py36_0
- xgboost=0.6a2=py36_0
- xz=5.2.2=0
- zeromq=4.2.1=1
- zlib=1.2.11=0
- pip:
  - civis==1.5.2
  - click==6.7
  - ipython-genutils==0.2.0
  - jsonref==0.1
  - jupyter-client==5.0.1
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.14
  - pyyaml==3.12
prefix: /Users/pskipper/miniconda3/envs/wbcd_demo

